package pharmacysystem;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;

import pharmacysystem.main;

/**
 *
 * @author Sujoy
 */
public class HOME extends javax.swing.JInternalFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String id_transfer;

    int day, month, year; // date declar golobaly
    //String monthly;

    public HOME() {
        initComponents();

        txt_discount.setEditable(false);
        btn_calculate.setEnabled(false);
        conn = DatabaseConnection.db_connect(); // database connection
        getInvoiceNo(); // invoice no get methode
        Fillcombo(); // show drug name in combo box
        txt_invoiceNO.disable(); // invoice no cant change
        cmb_drugName.requestFocus(); // focus to drug name with start program
        // get date from system
        Calendar cal = new GregorianCalendar();
        month = cal.get(Calendar.MONTH);
        year = cal.get(Calendar.YEAR);
        day = cal.get(Calendar.DAY_OF_MONTH);

        //main mn = new main();
    }

    public HOME(String id) {
        id_transfer = id;

        initComponents();
    }

    private void Fillcombo() {
        try {
            String sql = "select * from DrugEntry";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String drugname = rs.getString("DrugName");
                cmb_drugName.addItem(drugname);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                pst.close();
                rs.close();
            } catch (Exception e) {
            }
        }

    }

    public void calculateAmount() {

        txt_amountRS.setText(txt_amount.getText()); // get from amount and set to amount RS
        // calculate discount
        //convart to string to int
        double i = Double.parseDouble(txt_amountRS.getText()); // get amount rs
        double j = Double.parseDouble(txt_discount.getText()); // get discount

        String amount = String.valueOf(i); // convart result int to string 
        txt_payableAmount.setText(amount); // set amount at payable amount field

    }

    // get last invoice no from database
    public void getInvoiceNo() {
        String sql = "select max(InvoiceNo)as InvoiceNO from RetailSales";
        try {

            pst = conn.prepareStatement(sql);

            rs = pst.executeQuery();
            if (rs.next()) {
                int add = rs.getInt("InvoiceNo");
                int add1 = add + 1; // invoice no increase 
                txt_invoiceNO.setText("" + add1);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                pst.close();
                rs.close();
            } catch (Exception e) {
            }
        }
    }

    public void deleteTempData() {
        //delete temp data
        try {
            String sql = "delete from tempTable where InvoiceNo=?";

            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_invoiceNO.getText());

            pst.executeUpdate();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                pst.close();
                rs.close();
            } catch (Exception e) {
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmb_drugName = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txt_qty = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_mrp = new javax.swing.JTextField();
        txt_amount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_display = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btn_click = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btn_clear = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();
        btn_sane_print = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_amountRS = new javax.swing.JTextField();
        ckbox_discount = new javax.swing.JCheckBox();
        txt_discount = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_payableAmount = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_invoiceNO = new javax.swing.JTextField();
        txt_avail = new javax.swing.JLabel();
        txt_expDate = new javax.swing.JLabel();
        txt_batchNo = new javax.swing.JLabel();
        btn_calculate = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Retail Sales");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Enter Drug Name");

        cmb_drugName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cmb_drugName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Name" }));
        cmb_drugName.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmb_drugNamePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("QTY");

        txt_qty.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_qtyKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_qtyKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Avail");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("EXP Date");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Batch No");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("MRP");

        txt_mrp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txt_amount.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_amountActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Amount");

        btn_add.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_add.setText("Add >>");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        table_display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "QTY", "EXP Date", "Batch", "MRP", "Amount"
            }
        ));
        jScrollPane1.setViewportView(table_display);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Click To Remove Item");

        btn_click.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_click.setText("Click");
        btn_click.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clickActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Retail Sale");

        btn_clear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_save.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_print.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_print.setText("Print");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        btn_sane_print.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_sane_print.setText("Save & Print");
        btn_sane_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sane_printActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Amount    RS");

        txt_amountRS.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        ckbox_discount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ckbox_discount.setText("Discount");
        ckbox_discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbox_discountActionPerformed(evt);
            }
        });

        txt_discount.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_discount.setText("0");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("%");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Total  Payable Amount");

        txt_payableAmount.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Bill  Invoice No");

        txt_invoiceNO.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_invoiceNO.setForeground(new java.awt.Color(255, 51, 51));
        txt_invoiceNO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_invoiceNOKeyTyped(evt);
            }
        });

        txt_avail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_avail.setText("Avail");

        txt_expDate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_expDate.setText("exp");

        txt_batchNo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_batchNo.setText("batch");

        btn_calculate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_calculate.setText("Calculate");
        btn_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calculateActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Quit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_drugName, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txt_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_avail, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_expDate, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_batchNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_mrp, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_click, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(ckbox_discount))
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txt_discount, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                                    .addComponent(txt_amountRS))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel11))
                                            .addComponent(jLabel8))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_payableAmount)))
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)
                        .addComponent(jLabel13)
                        .addGap(32, 32, 32)
                        .addComponent(txt_invoiceNO, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_sane_print, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(txt_invoiceNO, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_expDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_avail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_drugName)
                    .addComponent(txt_qty)
                    .addComponent(txt_mrp)
                    .addComponent(txt_batchNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_amount, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_click, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_amountRS, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ckbox_discount)
                            .addComponent(txt_discount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_payableAmount)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_print, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_sane_print, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_calculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed

        String date = (day + "/" + month + "/" + year); // marge date
        // as 2017/4/17
        // save data into database 
        try {
            String sql = "insert into RetailSales (InvoiceNo,Amount,Date) values (?,?,?)";
            pst = conn.prepareStatement(sql);

            pst.setString(1, txt_invoiceNO.getText());
            pst.setString(2, txt_payableAmount.getText());
            pst.setString(3, date);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "saved");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                pst.close();
                rs.close();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // get data from field
        String name = cmb_drugName.getSelectedItem().toString();
        String batch = txt_batchNo.getText();
        String exp = txt_expDate.getText();
        String qty = txt_qty.getText();
        String mrp = txt_mrp.getText();
        String amount = txt_amount.getText();
        // set data in the table
        DefaultTableModel d = (DefaultTableModel) table_display.getModel();
        d.addRow(new Object[]{name, qty, exp, batch, mrp, amount});

        calculateAmount(); // amount calculation method
        // save temp data into database
        try {
            String sql = "insert into tempTable (InvoiceNo, Amount) values(?,?)";
            pst = conn.prepareStatement(sql);

            pst.setString(1, txt_invoiceNO.getText());
            pst.setString(2, txt_amount.getText());

            pst.execute();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                pst.close();
                rs.close();
            } catch (Exception e) {
            }
        }

        //calculate total amount 
        //set amount RS
        try {
            String sql2 = "select SUM(Amount) from tempTable where InvoiceNo =?";
            pst = conn.prepareStatement(sql2);

            pst.setString(1, txt_invoiceNO.getText());

            rs = pst.executeQuery();
            if (rs.next()) {
                String add = rs.getString("SUM(Amount)");
                txt_amountRS.setText(add);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                pst.close();
                rs.close();
            } catch (Exception e) {
            }
        }

// clear field
        txt_amount.setText("");
        cmb_drugName.setSelectedIndex(0);
        txt_batchNo.setText("");
        txt_qty.setText("");
        txt_mrp.setText("");
        txt_expDate.setText("");
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_clickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clickActionPerformed
        DefaultTableModel d = (DefaultTableModel) table_display.getModel();
        // remove row from the table
        try {
            int SelectedRowIndex = table_display.getSelectedRow();
            d.removeRow(SelectedRowIndex);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                pst.close();
                rs.close();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btn_clickActionPerformed

    private void txt_invoiceNOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_invoiceNOKeyTyped
        //txt_invoiceNO.disable();
    }//GEN-LAST:event_txt_invoiceNOKeyTyped

    private void btn_sane_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sane_printActionPerformed
        {
            String bl_no = txt_invoiceNO.getText();
            String date = (day + "," + month + "," + year); // marge date
            // save data into database 
            try {
                String sql = "insert into RetailSales (InvoiceNo,Amount,Date) values (?,?,?)";
                pst = conn.prepareStatement(sql);

                pst.setString(1, txt_invoiceNO.getText());
                pst.setString(2, txt_payableAmount.getText());
                pst.setString(3, date);

                pst.execute();
                JOptionPane.showMessageDialog(null, "saved");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } finally {
                main mn = new main();
                mn.display();
                try {
                    rs.close();
                    pst.close();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }

        }


    }//GEN-LAST:event_btn_sane_printActionPerformed

    private void ckbox_discountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbox_discountActionPerformed
        if (ckbox_discount.isSelected()) {
            txt_discount.setEditable(true);
            btn_calculate.setEnabled(true);
        } else {
            txt_discount.setEditable(false);
        }
    }//GEN-LAST:event_ckbox_discountActionPerformed

    private void txt_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_amountActionPerformed
        // press enter to add

    }//GEN-LAST:event_txt_amountActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        Bill bl = new Bill();

        bl.show();
    }//GEN-LAST:event_btn_printActionPerformed

    private void cmb_drugNamePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmb_drugNamePopupMenuWillBecomeInvisible
        String tmp = (String) cmb_drugName.getSelectedItem();
        String sql = "select * from DrugEntry where DrugName=?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, tmp);
            rs = pst.executeQuery();

            if (rs.next()) {
                String addd1 = rs.getString("ExpDate");
                txt_expDate.setText(addd1);
                String add1 = rs.getString("BatchNo");
                txt_batchNo.setText(add1);
                String add2 = rs.getString("MRP");
                txt_mrp.setText(add2);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }

        }

    }//GEN-LAST:event_cmb_drugNamePopupMenuWillBecomeInvisible

    private void txt_qtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_qtyKeyReleased
        // calculate mrp and qty and set in amount box

        double qty = Double.parseDouble(txt_qty.getText());
        double mrp = Double.parseDouble(txt_mrp.getText());
        double i = qty * mrp;
        String result = String.valueOf(i);
        txt_amount.setText(result);
    }//GEN-LAST:event_txt_qtyKeyReleased

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        txt_amount.setText("");
        txt_amountRS.setText("");
        txt_avail.setText("");
        txt_batchNo.setText("");
        txt_discount.setText("");
        txt_expDate.setText("");
        txt_payableAmount.setText("");
        txt_mrp.setText("");
        txt_qty.setText("");
        cmb_drugName.setSelectedIndex(0);
        getInvoiceNo();


    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calculateActionPerformed
        double amountRS = Double.parseDouble(txt_amountRS.getText());
        double discountA = Double.parseDouble(txt_discount.getText());
        double cal = (amountRS * discountA) / 100;
        String s = String.valueOf(cal);
        txt_payableAmount.setText(s);


    }//GEN-LAST:event_btn_calculateActionPerformed

    private void txt_qtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_qtyKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // get data from field
            String name = cmb_drugName.getSelectedItem().toString();
            String batch = txt_batchNo.getText();
            String exp = txt_expDate.getText();
            String qty = txt_qty.getText();
            String mrp = txt_mrp.getText();
            String amount = txt_amount.getText();
            // set data in the table
            DefaultTableModel d = (DefaultTableModel) table_display.getModel();
            d.addRow(new Object[]{name, qty, exp, batch, mrp, amount});

            calculateAmount(); // amount calculation method
            // clear field
            txt_amount.setText("");
            cmb_drugName.setSelectedIndex(0);
            txt_batchNo.setText("");
            txt_qty.setText("");
            txt_mrp.setText("");
            txt_expDate.setText("");

        }
    }//GEN-LAST:event_txt_qtyKeyPressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
            super.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_calculate;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_click;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_sane_print;
    private javax.swing.JButton btn_save;
    private javax.swing.JCheckBox ckbox_discount;
    private javax.swing.JComboBox cmb_drugName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_display;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_amountRS;
    private javax.swing.JLabel txt_avail;
    private javax.swing.JLabel txt_batchNo;
    private javax.swing.JTextField txt_discount;
    private javax.swing.JLabel txt_expDate;
    private javax.swing.JTextField txt_invoiceNO;
    private javax.swing.JTextField txt_mrp;
    private javax.swing.JTextField txt_payableAmount;
    private javax.swing.JTextField txt_qty;
    // End of variables declaration//GEN-END:variables
}
